LocaleString = {
"%challenges": "dəvət",
"%isonline": "online",
"%like_list": "siyahı",
"%likes": "xoşuma gəldi",
"%notifications": "bildiriş",
"%new_challenge": "var yeni problem!",
"%new_msg": "yeni mesaj",
"%me": "mən",
"%write_comment": "Yazmaq comment...",
"%write_wall": "yazmaq divar",
"%challenge": "meydan",
"%cannotabort": "siz dayandırmaq bilməz, cari oyunları",
"%error": "bug",
"%areyousure": "əminsinizmi?",
"%rating": "reytinq",
"%rating_month": "aylıq reytinq",
"%rating_blitz": "reytinqini blitz",
"%rating_crazy": "reytinqini vəhşi",
"%firstnameerr": "adınızı etibarlı deyil.",
"%lastnameerr": "sizin soyadı etibarlıdır.",
"%passworderr": "parolu olmalıdır 4-dən 16 simvol.",
"%termserr": "bizim qəbul qaydaları",
"%errorintheform": "doğru və səhv şəklində.",
"%acceptdraw": "təklifini qəbul çəkmək.",
"%drawaccepted": "сожительствуем qəbul edilib",
"%whitesturn": "Ağ tərəqqi",
"%blacksturn": "qara kurs",
"%uwonthegame": "siz qalib. ",
"%game_ended": "oyun bitdi",
"%flag": "vaxt gəldi. ",
"%yourturn": "öz növbəsində",
"%opponentturn": "rəqib",
"%opponentnotready": "rəqib heç də qoşulub edib!",
"%newgameinfo": "əldə etmək üçün oyunlara ; ",
"%youhavenewgame": "var, yeni oyun!",
"%acceptinvitation": "dəvəti qəbul",
"%reject": "rədd etmək",
"%withdraw": "çıxarmaq",
"%rejectedinvitation": "matça dəvət onlar",
"%rematch": "intiqam",
"%play": "oyun",
"%yourmatch": "matç...",
"%drawrequest": "rəqib var сожительствуем. Əgər siz hərəkət, təklif olunacaq rədd edilir. Qəbul?",
"%drawrequestwaiting": "sizin sorğu gözləyirdilər",
"%session_timeout": "taym-aut sessiyasında",
"%done": "əməliyyat başa çatıb",
"%board": "təsnif",
"%selectall": "qeyd hamı",
"%deselectall": "ləğv hamı",
"%fill_all": "doldurmaq lazım olan bütün sahələri",
"%loading": "yükləmə",
"%system_message": "sistemli post",
"%waiting": "cavab ərəfəsində",
"%invite_to_my_buddies": "sorğu dostluğu",
"%total_time_limit": "ümumi zaman limiti",
"%time_limit": "zaman limiti",
"%official": "reytinq",
"%notofficial": "qiymət",
"%min": "bir dəqiqə",
"%standard": "standart",
"%blitz": "blitz",
"%crazyhouse": "дурдом",
"%chess960": "Fişer",
"%3check": "3 Yoxlamaq",
"%invalid_move": "səhv hərəkət",
"%conn_lost": "keçid itirilmişdir",
"%challenge_onfb": "göndərmək dostları Facebook",
"%playon": "şahmat oynamaq üçün ChessMoon!",
"%sending": "tapşırıq",
"%resending": "təkrar göndərilməsi",
"%send_to_fb": "göndərmək Facebook",
"%enter_pool": "daxil lobbisi",
"%exit_pool": "lobbisinin-çıxış",
"%letsplay": "birinci kim klik burada oynamaq olar şahmat mənimlə!",
"%bepremium": "biz ümid edirik ki, xoşunuza gəlirmi bizim saytda. Biz əminik, siz də razı olarsınız ki, bir çox məzmun burada, və siz təsəvvür edə bilərsiniz kimi bizim bir çox yüzlərlə saat iş üçün birlikdə bütün qoymaq. Bu da oldu bizim məqsədimiz saxlamaq üçün mümkün qədər sərbəst və bu günə qədər çox yaxşı, lakin bu, həqiqətən, maliyyə dəstəyinə ehtiyacı vardır, yaşamaq üçün...<a href='premium.php'>aradan qaldırmaq üçün bu məhdudiyyət üzvü olan mükafat.</a>",
"%nogames": "biz heç var oyunlar.",
"%noplayers": "no oyunçular",
"%opponent": "düşmən",
"%timecontrol": "zaman nəzarət",
"%lastmove": "Sonuncu kurs",
"%result": "nəticə",
"%rating_change": "dəyişiklik reytinq",
"%enddate": "bitmə tarixi",
"%details": "ətraflı",
"%level": "səviyyəsi",
"%day": "gün",
"%archives": "arxiv",
"%sendmessage": "mesaj Göndər",
"%lesson": "dərs",
"%activate_sound": "yandırmaq üçün səs"
};