var LocaleString = [];LocaleString = {
"%challenges": "Invitacions",
"%isonline": "està en línia",
"%like_list": "Com una Llista",
"%likes": "usuari li agradava",
"%notifications": "Notificacions",
"%new_challenge": "Vostès tenen un nou Repte!",
"%new_msg": "Missatge Nou",
"%me": "I",
"%write_comment": "Escriure un comentari...",
"%write_wall": "Escriure en la Paret",
"%challenge": "Repte",
"%cannotabort": "no Es pot avortar en curs partits",
"%error": "Error",
"%areyousure": "esteu segur?",
"%rating": "Rating",
"%rating_month": "Mensual de Qualificació",
"%rating_blitz": "Blitz de Qualificació",
"%rating_crazy": "Wild Qualificació",
"%firstnameerr": "la Teva forename no és vàlid.",
"%lastnameerr": "el cognom no és vàlid.",
"%passworderr": "la Seva contrasenya ha de tenir entre 4 i 16 caràcters.",
"%termserr": "si us Plau, accepti les nostres normes.",
"%errorintheform": "si us Plau, corregiu els errors en el formulari.",
"%acceptdraw": "Acceptar dibuixar oferta.",
"%drawaccepted": "Dibuixar oferta acceptada",
"%whitesturn": "Blanc Torn",
"%blacksturn": "Black Torn",
"%uwonthegame": "Heu Guanyat. ",
"%game_ended": "Joc va Acabar",
"%flag": "Time Out. ",
"%yourturn": "el Teu Torn",
"%opponentturn": "àrea Rival de Torn",
"%opponentnotready": "el Seu rival no ha connectat a partit!",
"%newgameinfo": "Per accedir als jocs ; ",
"%youhavenewgame": "teniu un nou joc!",
"%acceptinvitation": "Acceptar Partit Invitació",
"%reject": "Rebutjar",
"%withdraw": "Retirar",
"%rejectedinvitation": "Partit invitació Ignorat",
"%rematch": "Revenja",
"%play": "Jugar",
"%yourmatch": "el Seu partit...",
"%drawrequest": "el Teu adversari té un sorteig oferta. Si es mou, l'oferta serà denegada. Acceptar?",
"%drawrequestwaiting": "El sorteig de sol·licitud està a l'espera",
"%session_timeout": "Sessió de temps d'Espera",
"%done": "Operació",
"%board": "Consell",
"%selectall": "Selecciona-ho Tot",
"%deselectall": "Deseleccionar-les Totes",
"%fill_all": "Omplir tots els camps obligatoris",
"%loading": "Càrrega",
"%system_message": "Sistema de Missatge",
"%waiting": "a l'Espera de Resposta",
"%invite_to_my_buddies": "l'Amistat Petició",
"%total_time_limit": "Temps Total Límit",
"%time_limit": "Temps Límit",
"%official": "Classificat",
"%notofficial": "No Catalogat",
"%min": "Minuts",
"%standard": "Estàndard",
"%blitz": "Blitz",
"%crazyhouse": "Crazyhouse",
"%chess960": "Fischer",
"%3check": "3 Fes",
"%invalid_move": "Invalid Moure",
"%conn_lost": "Connexió s'ha perdut.",
"%challenge_onfb": "Enviar a Amics a Facebook",
"%playon": "Jugar a Escacs en ChessMoon!",
"%sending": "Enviar",
"%resending": "Resending",
"%send_to_fb": "Enviar a Facebook",
"%enter_pool": "Introduïu el Vestíbul",
"%exit_pool": "Sortida Lobby",
"%letsplay": "El primer que faci clic aquí pot jugar a un joc d'Escacs amb mi!",
"%bepremium": "esperem que estan gaudint del nostre lloc web. Estem segurs que vostè estarà d'acord que hi ha un munt de contingut aquí, i com us podeu imaginar que ens ha portat molts centenars d'hores de feina per posar-ho tots junts. Es va convertir en el nostre objectiu de mantenir tant lliure com sigui possible, i que va molt bé fins ara, però sí que necessiten suport econòmic per sobreviure...<a href='premium.php'>Superar aquesta restricció per ser un membre premium.</a>",
"%nogames": "no Has de jocs.",
"%noplayers": "ja No hi ha jugadors",
"%opponent": "Oponent",
"%timecontrol": "Control de Temps",
"%lastmove": "Últim Moviment",
"%result": "Resultat",
"%rating_change": "Canvi de Qualificació",
"%enddate": "Data de Finalització",
"%details": "Detalls",
"%level": "de Nivell",
"%day": "Dia",
"%archives": "Arxius",
"%sendmessage": "Enviar Missatge",
"%lesson": "la Lliçó",
"%activate_sound": "Activar el So"
};