var LocaleString = [];LocaleString = {
"%challenges": "دعوات",
"%isonline": "هو على الانترنت" ,
"%like_list": "مثل قائمة" ,
"%likes": "المستخدم يحب",
"%notifications": "التبليغات" ,
"%new_challenge": "كنت قد التحدي الجديد!",
"%new_msg": "رسالة جديدة",
"%me": "أنا",
"%write_comment": "أكتب تعليق...",
"%write_wall": "الكتابة على الجدار",
"%challenge": "التحدي",
"%cannotabort": "لا يمكن إحباط الجارية مباريات",
"%error": "حدث خطأ",
"%areyousure": "هل أنت متأكد؟",
"%rating": "التقييم",
"%rating_month": "الشهرية التقييم",
"%rating_blitz": "الغارة التقييم",
"%rating_crazy": "البرية التقييم",
"%firstnameerr": "الاسم الخاص بك غير صالحة.",
"%lastnameerr": "اللقب الخاص بك غير صالحة.",
"%passworderr": "كلمة السر يجب أن يكون بين 4 و 16 حرفا.",
"%termserr": "أرجو أن تقبل القواعد.",
"%errorintheform": "يرجى تصحيح الأخطاء في شكل.",
"%acceptdraw": "تقبل رسم العرض.",
"%drawaccepted": "رسم نقدم المقبولة",
"%whitesturn": "الأبيض بدورها",
"%blacksturn": "الأسود بدورها",
"%uwonthegame": "لن. ",
"%game_ended": "اللعبة انتهت",
"%flag": "الوقت. ",
"%yourturn": "دورك",
"%opponentturn": "الخصم بدوره",
"%opponentnotready": "الخصم الخاص بك ليس متصلا المباراة!",
"%newgameinfo": "الوصول إلى الألعاب.",
"%youhavenewgame": "لديك لعبة جديدة!",
"%acceptinvitation": "قبول مباراة دعوة",
"%reject": "رفض",
"%withdraw": "الانسحاب",
"%rejectedinvitation": "المباراة دعوة تجاهل",
"%rematch": "مباراة العودة",
"%play": "مسرحية",
"%yourmatch": "مباراة الخاص بك...",
"%drawrequest": "خصمك التعادل العرض. إذا قمت بنقل العرض سيتم رفض. تقبل؟",
"%drawrequestwaiting": "التعادل طلب الانتظار",
"%session_timeout": "الدورة مهلة",
"%done": "العملية أنجزت",
"%board": "المجلس",
"%selectall": "تحديد الكل",
"%deselectall": "إلغاء تحديد الكل",
"%fill_all": "ملء جميع الحقول المطلوبة",
"%loading": "تحميل",
"%system_message": "النظام رسالة",
"%waiting": "في انتظار الاستجابة",
"%invite_to_my_buddies": "طلب صداقة",
"%total_time_limit": "إجمالي الوقت الحد",
"%time_limit": "الوقت الحد",
"%official": "تصنيف",
"%notofficial": "لا تصنيف",
"%min": "دقيقة",
"%standard": "المعيار",
"%blitz": "الغارة",
"%crazyhouse": "Crazyhouse",
"%chess960": "فيشر",
"%3check": "3 تحقق",
"%invalid_move": "صالح التحرك",
"%conn_lost": "اتصال قد فقدت.",
"%challenge_onfb": "أرسل إلى أصدقائك على Facebook",
"%playon": "تلعب الشطرنج على ChessMoon!",
"%sending": "إرسال",
"%resending": "إرسال",
"%send_to_fb": "إرسال إلى Facebook",
"%enter_pool": "تدخل اللوبي",
"%exit_pool": "خروج اللوبي",
"%letsplay": "أول من النقرات هنا يمكن أن تلعب لعبة الشطرنج مع لي!",
"%bepremium": "نحن نأمل كنت تتمتع موقعنا. نحن على يقين من أنك سوف نتفق على أن هناك الكثير من المحتوى هنا, كما يمكنك أن تتخيل أنها اتخذت لنا العديد من مئات الساعات من العمل لوضع كل ذلك معا. أصبح هدفنا للحفاظ على قدر مجانا ممكن انها تسير بشكل جيد حتى الآن ، ولكنه بحاجة إلى دعم مالي من أجل البقاء...<a href='premium.php'>التغلب على هذا العائق من خلال كونها عضوا.</a>",
"%nogames": "ليس لديك الألعاب.",
"%noplayers": "كلا اللاعبين",
"%opponent": "الخصم",
"%timecontrol": "الوقت السيطرة",
"%lastmove": "الخطوة الأخيرة",
"%result": "النتيجة",
"%rating_change": "تصنيف التغيير",
"%enddate": "نهاية التاريخ",
"%details": "تفاصيل",
"%level": "المستوى",
"%day": "يوم",
"%archives": "أرشيف",
"%sendmessage": "إرسال رسالة",
"%lesson": "الدرس",
"%activate_sound": "تفعيل الصوت"
};